import { migrateProfiles } from './profile-migration';
import { db, transaction } from './db';
const tables = [
`CREATE TABLE IF NOT EXISTS ce_schools (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS ce_users (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES ce_schools(id), name TEXT NOT NULL, email TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('cobranza','seguimiento','directora')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, UNIQUE(school_id,email), UNIQUE(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES ce_users(id), csrf TEXT NOT NULL, expires_at TEXT NOT NULL, absolute_expires_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS ce_login_attempts (key_hash TEXT PRIMARY KEY, attempts INTEGER NOT NULL, reset_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS ce_guardians (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES ce_schools(id), name TEXT NOT NULL, email TEXT, phone TEXT, email_consent INTEGER NOT NULL DEFAULT 0, whatsapp_consent INTEGER NOT NULL DEFAULT 0, consent_note TEXT, created_at TEXT NOT NULL, UNIQUE(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_students (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, guardian_id TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, grade TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(school_id,code), UNIQUE(school_id,id), FOREIGN KEY(school_id,guardian_id) REFERENCES ce_guardians(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_invoices (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, student_id TEXT NOT NULL, reference TEXT NOT NULL, concept TEXT NOT NULL, due_date TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), late_fee_cents INTEGER NOT NULL DEFAULT 0 CHECK(late_fee_cents>=0), paid_cents INTEGER NOT NULL DEFAULT 0 CHECK(paid_cents>=0 AND paid_cents<=amount_cents+late_fee_cents), created_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(school_id,reference), UNIQUE(school_id,id), FOREIGN KEY(school_id,student_id) REFERENCES ce_students(school_id,id), FOREIGN KEY(school_id,created_by) REFERENCES ce_users(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_payments (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, invoice_id TEXT NOT NULL, request_key TEXT NOT NULL, reference TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), method TEXT NOT NULL, paid_on TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(school_id,request_key), UNIQUE(school_id,reference), FOREIGN KEY(school_id,invoice_id) REFERENCES ce_invoices(school_id,id), FOREIGN KEY(school_id,created_by) REFERENCES ce_users(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_promises (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, invoice_id TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), baseline_paid_cents INTEGER NOT NULL, due_date TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pendiente', notes TEXT, created_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(school_id,id), FOREIGN KEY(school_id,invoice_id) REFERENCES ce_invoices(school_id,id), FOREIGN KEY(school_id,created_by) REFERENCES ce_users(school_id,id))`,
`CREATE UNIQUE INDEX IF NOT EXISTS ce_one_active_promise ON ce_promises(school_id,invoice_id) WHERE status='pendiente'`,
`CREATE TABLE IF NOT EXISTS ce_calls (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, guardian_id TEXT NOT NULL, outcome TEXT NOT NULL, notes TEXT, next_contact TEXT, created_by TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(school_id,guardian_id) REFERENCES ce_guardians(school_id,id), FOREIGN KEY(school_id,created_by) REFERENCES ce_users(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_outbox (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES ce_schools(id), dedupe_key TEXT NOT NULL, promise_id TEXT, user_id TEXT, channel TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pendiente', body TEXT, provider_id TEXT, error_code TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(school_id,dedupe_key), FOREIGN KEY(school_id,promise_id) REFERENCES ce_promises(school_id,id), FOREIGN KEY(school_id,user_id) REFERENCES ce_users(school_id,id))`,
`CREATE TABLE IF NOT EXISTS ce_audit (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES ce_schools(id), actor_id TEXT, action TEXT NOT NULL, entity_id TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(school_id,actor_id) REFERENCES ce_users(school_id,id))`,
`CREATE INDEX IF NOT EXISTS ce_invoice_due ON ce_invoices(school_id,due_date)`,
`CREATE INDEX IF NOT EXISTS ce_calls_followup ON ce_calls(school_id,next_contact)`,
`CREATE INDEX IF NOT EXISTS ce_audit_school ON ce_audit(school_id,created_at)`,
];
export async function migrate() {
  await transaction(async(tx)=>{for(const sql of tables) await tx.run(sql);await migrateProfiles(tx,!!process.env.DATABASE_URL);});
  // Supabase REST roles never receive access to these application-owned tables.
  if(process.env.DATABASE_URL) await db.run(`DO $$ DECLARE t record; r text; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'ce_%' LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t.tablename); FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I',t.tablename,r); END IF; END LOOP; END LOOP; END $$`);
}
