import { notFound } from 'next/navigation';
import Link from 'next/link';
import { requireActor } from '@/lib/auth';
import { getData } from '@/lib/collections';
import { balance,money } from '@/lib/domain';
import { Shell } from '@/components/shell';
import { Form,Field } from '@/components/form';
export const dynamic='force-dynamic';
export default async function GuardianPage({params}:{params:Promise<{id:string}>}) {
 const actor=await requireActor(),{id}=await params,d=await getData(actor),g=d.guardians.find(g=>g.id===id);if(!g)notFound();
 const invoices=d.invoices.filter(i=>i.guardian_id===id),invoiceIds=new Set(invoices.map(i=>i.id));
 const history=[...d.calls.filter(c=>c.guardian_id===id).map(c=>({id:c.id,date:c.created_at,title:`Llamada · ${c.outcome}`,detail:`${c.author} · ${c.notes||'Sin notas'}`})),...d.payments.filter(p=>invoiceIds.has(p.invoice_id)).map(p=>({id:p.id,date:p.created_at,title:`Pago recibido · ${money(p.amount_cents)}`,detail:`${p.author} · ${p.reference}`}))].sort((a,b)=>b.date.localeCompare(a.date));
 return <Shell actor={actor} section="acudientes"><Link className="text-link" href="/acudientes">Volver a acudientes</Link><div className="page-heading"><div><span className="eyebrow">FICHA DEL ACUDIENTE</span><h1>{g.name}</h1><p>{g.email||'Sin correo'} · {g.phone||'Sin teléfono'}</p></div><div className="balance-box"><small>Saldo actual</small><strong>{money(invoices.reduce((a,i)=>a+balance(i),0))}</strong></div></div><div className="detail-grid"><section className="card detail-card"><h2>Estado de cuenta</h2>{invoices.map(i=><div className="account-line" key={i.id}><div><strong>{i.student_name}</strong><small>{i.concept} · Vence {i.due_date}</small><small>Cargo {money(i.amount_cents)} + mora {money(i.late_fee_cents)} − abonos {money(i.paid_cents)}</small></div><strong>{money(balance(i))}</strong></div>)}{!invoices.length&&<p className="empty">Sin cuentas registradas.</p>}<h2>Promesas</h2>{d.promises.filter(p=>invoiceIds.has(p.invoice_id)).map(p=><p key={p.id}>{p.due_date} · {money(p.amount_cents)} · {p.status}</p>)}</section><section className="card detail-card"><h2>Historial de gestión</h2><div className="timeline">{history.map(h=><div key={h.id}><span className="timeline-dot"/><div><strong>{h.title}</strong><p>{h.detail}</p><small>{new Intl.DateTimeFormat('es-PA',{dateStyle:'short',timeStyle:'short',timeZone:'America/Panama'}).format(new Date(h.date))}</small></div></div>)}</div>{!history.length&&<p className="empty">Aún no hay gestiones.</p>}</section></div>{actor.role==='cobranza'&&<section className="card detail-card"><h2>Preferencias de contacto</h2><p>Permite registrar o retirar la autorización de los recordatorios.</p><Form action="consent" csrf={actor.csrf}><input type="hidden" name="guardian_id" value={id}/><label className="check"><input type="checkbox" name="email_consent" defaultChecked={!!g.email_consent}/> Recordatorios por email</label><label className="check"><input type="checkbox" name="whatsapp_consent" defaultChecked={!!g.whatsapp_consent}/> Recordatorios por WhatsApp</label><Field label="Evidencia / motivo del cambio" name="consent_note" defaultValue={g.consent_note||''}/></Form></section>}</Shell>;
}
