import Link from 'next/link';
import { notFound } from 'next/navigation';
import { randomUUID } from 'node:crypto';
import { requireActor } from '@/lib/auth';
import { getData } from '@/lib/collections';
import { balance,money,today,daysLate,status } from '@/lib/domain';
import { Shell,labels } from '@/components/shell';
import { Form,Field,Select } from '@/components/form';
import { Importer } from '@/components/importer';
import { staffActivity } from '@/lib/reports';
export const dynamic='force-dynamic';
export default async function Section({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{q?:string;estado?:string}>}) {
 const {section}=await params;if(!labels[section]||section==='dashboard')notFound();const actor=await requireActor();if(section==='importar'&&actor.role!=='cobranza')notFound();
 const d=await getData(actor),query=await searchParams,q=(query.q||'').toLowerCase();
 const guardians=d.guardians.map(g=>({value:g.id,label:g.name})),students=d.students.map(s=>({value:s.id,label:`${s.code} · ${s.name}`})),invoices=d.invoices.filter(i=>balance(i)>0).map(i=>({value:i.id,label:`${i.reference} · ${i.student_name} · ${money(balance(i))}`}));
 const filtered=d.invoices.filter(i=>`${i.guardian_name} ${i.student_name} ${i.reference}`.toLowerCase().includes(q)).filter(i=>!query.estado||query.estado==='todos'||(query.estado==='pagado'?balance(i)===0:query.estado==='promesa'?d.promises.some(p=>p.invoice_id===i.id&&p.status==='pendiente'):balance(i)>0&&daysLate(i.due_date)>=Number(query.estado)));
 const notes=<label className="field full">Notas<textarea name="notes" maxLength={2000} rows={3}/></label>;
 return <Shell actor={actor} section={section}><div className="page-heading"><div><span className="eyebrow">GESTIÓN DEL COLEGIO</span><h1>{labels[section]}</h1><p>{section==='recordatorios'?'Control de avisos y resultado de los envíos.':section==='reportes'?'Cartera, recuperación y actividad del equipo.':'Consulta la información y registra cada movimiento.'}</p></div>{['cobros','reportes'].includes(section)&&<a className="button secondary" href="/api/export?format=xlsx">Exportar Excel</a>}</div>
 {section==='cobros'&&<><form className="filters"><input aria-label="Buscar cuentas" name="q" placeholder="Buscar acudiente, estudiante o referencia…" defaultValue={q}/><select aria-label="Filtrar estado" name="estado" defaultValue={query.estado||'todos'}><option value="todos">Todos los estados</option><option value="1">Vencidos</option><option value="31">Más de 30 días</option><option value="61">Más de 60 días</option><option value="91">Más de 90 días</option><option value="promesa">Promesa abierta</option><option value="pagado">Pagados</option></select><button className="button secondary">Filtrar</button></form><Table headers={['Cuenta / estudiante','Acudiente','Vencimiento','Cargo + mora','Abonado','Saldo','Estado']} rows={filtered.map(i=>[<><strong>{i.reference}</strong><small>{i.student_name} · {i.concept}</small></>,<Link href={`/acudientes/${i.guardian_id}`}>{i.guardian_name}</Link>,i.due_date,<>{money(i.amount_cents)}<small>Mora: {money(i.late_fee_cents)}</small></>,money(i.paid_cents),<strong>{money(balance(i))}</strong>,<span className={`badge ${balance(i)===0?'good':daysLate(i.due_date)>0?'danger':'warning'}`}>{status(i)}</span>])}/>{actor.role==='cobranza'&&<Editor title="Registrar cuenta por cobrar"><Form action="invoice" csrf={actor.csrf}><Select name="student_id" label="Estudiante" options={students}/><Field name="reference" label="Referencia única" placeholder="MEN-2026-10-001"/><Field name="concept" label="Concepto" placeholder="Mensualidad octubre"/><Field name="due_date" label="Vencimiento" type="date"/><Field name="amount" label="Monto (B/.)" placeholder="400.00"/><Field name="late_fee" label="Mora aprobada (B/.)" defaultValue="0.00"/><p className="help full">La mora se registra expresamente. No se aplican porcentajes automáticos hasta definir la política del colegio.</p></Form></Editor>}</>}
 {section==='acudientes'&&<><Table headers={['Nombre','Correo','Teléfono','Canales autorizados','Ficha']} rows={d.guardians.map(g=>[g.name,g.email||'—',g.phone||'—',[g.email_consent?'Email':'',g.whatsapp_consent?'WhatsApp':''].filter(Boolean).join(' · ')||'Sin autorización',<Link className="text-link" href={`/acudientes/${g.id}`}>Ver historial</Link>])}/>{actor.role==='cobranza'&&<Editor title="Registrar acudiente"><Form action="guardian" csrf={actor.csrf}><Field label="Nombre completo" name="name"/><Field label="Correo" name="email" type="email" required={false}/><Field label="WhatsApp" name="phone" placeholder="+50761234567" required={false}/><Field label="Evidencia de autorización" name="consent_note" placeholder="Fecha y origen de la autorización" required={false}/><label className="check"><input type="checkbox" name="email_consent"/> Autoriza recordatorios por email</label><label className="check"><input type="checkbox" name="whatsapp_consent"/> Autoriza recordatorios por WhatsApp</label></Form></Editor>}</>}
 {section==='estudiantes'&&<><Table headers={['Código','Estudiante','Grado','Acudiente']} rows={d.students.map(s=>[s.code,s.name,s.grade,s.guardian_name])}/>{actor.role==='cobranza'&&<Editor title="Registrar estudiante"><Form action="student" csrf={actor.csrf}><Field label="Código único" name="code"/><Field label="Nombre completo" name="name"/><Field label="Grado / sección" name="grade"/><Select label="Acudiente responsable" name="guardian_id" options={guardians}/></Form></Editor>}</>}
 {section==='pagos'&&<><div className="notice">Los pagos y abonos reducen el saldo de una cuenta específica. Los registros confirmados se conservan para auditoría.</div><Table headers={['Fecha de pago','Referencia','Estudiante','Monto','Método','Registrado por']} rows={d.payments.map(p=>[p.paid_on,p.reference,p.student_name,money(p.amount_cents),p.method,p.author])}/>{actor.role==='cobranza'&&<Editor title="Registrar pago o abono"><Form action="payment" csrf={actor.csrf}><input type="hidden" name="request_key" value={randomUUID()}/><Select label="Cuenta por cobrar" name="invoice_id" options={invoices}/><Field label="Monto recibido (B/.)" name="amount"/><Field label="Referencia del recibo / transacción" name="reference"/><Field label="Fecha de pago" name="paid_on" type="date" defaultValue={today()}/><Select label="Método de pago" name="method" options={['Transferencia','Efectivo','Tarjeta','ACH','Yappy'].map(s=>({value:s,label:s}))}/></Form></Editor>}</>}
 {section==='promesas'&&<><Table headers={['Acudiente / estudiante','Compromiso','Fecha prometida','Pendiente de promesa','Estado']} rows={d.promises.map(p=>[<>{p.guardian_name}<small>{p.student_name}</small></>,money(p.amount_cents),p.due_date,money(Math.max(0,p.amount_cents-(p.paid_cents-p.baseline_paid_cents))),<span className={`badge ${p.status==='cumplida'?'good':p.status==='pendiente'&&p.due_date<today()?'danger':'warning'}`}>{p.status==='pendiente'&&p.due_date<today()?'Incumplida':p.status}</span>])}/>{actor.role==='seguimiento'&&<><Editor title="Registrar promesa de pago"><Form action="promise" csrf={actor.csrf}><Select label="Cuenta" name="invoice_id" options={invoices}/><Field label="Monto prometido (B/.)" name="amount"/><Field label="Fecha prometida" name="due_date" type="date"/>{notes}<p className="help full">Recordatorio tres días antes. Si se registra con menos anticipación, se programa para la próxima ejecución. Los abonos posteriores se aplican al compromiso.</p></Form></Editor><Editor title="Cancelar o sustituir un compromiso"><Form action="cancel-promise" csrf={actor.csrf} label="Cancelar promesa"><Select label="Promesa abierta" name="promise_id" options={d.promises.filter(p=>p.status==='pendiente').map(p=>({value:p.id,label:`${p.guardian_name} · ${p.due_date} · ${money(p.amount_cents)}`}))}/><Field label="Motivo de cancelación" name="reason"/></Form></Editor></>}</>}
 {section==='llamadas'&&<><Table headers={['Acudiente','Resultado','Notas','Próximo contacto','Fecha / responsable']} rows={d.calls.map(c=>[<Link href={`/acudientes/${c.guardian_id}`}>{c.guardian_name}</Link>,c.outcome,c.notes||'—',c.next_contact||'—',<>{formatDate(c.created_at)}<small>{c.author}</small></>])}/>{actor.role==='seguimiento'&&<Editor title="Registrar llamada"><Form action="call" csrf={actor.csrf}><Select label="Acudiente" name="guardian_id" options={guardians}/><Select label="Resultado" name="outcome" options={['Contestó','No contestó','Número incorrecto','Llamar nuevamente','Promesa de pago','Acuerdo de pago'].map(s=>({value:s,label:s}))}/><Field label="Próximo seguimiento" name="next_contact" type="date" required={false}/>{notes}<p className="help full">Si se acordó un pago, registra también su monto y fecha en Promesas de pago.</p></Form></Editor>}</>}
 {section==='recordatorios'&&<><div className="notice">{process.env.SEND_ENABLED==='true'?'Envíos habilitados. Solo se contacta a acudientes con autorización registrada.':'Envíos desactivados. Los avisos se preparan sin contactar a las familias.'} El estado «Aceptado por proveedor» no confirma entrega ni lectura.</div><Table headers={['Creado','Canal','Estado','Observación']} rows={d.outbox.map(n=>[formatDate(n.created_at),n.channel,<span className={`badge ${n.status==='aceptado_proveedor'?'good':'warning'}`}>{n.status.replaceAll('_',' ')}</span>,n.error_code?'Revisar con el proveedor antes de cualquier reenvío':'—'])}/><p className="help">Los mensajes pagados, cancelados o sin consentimiento se descartan antes del envío. Un registro en «procesando» que no avance debe revisarse, sin reenviarlo automáticamente.</p></>}
 {section==='reportes'&&<><div className="report-actions"><a className="button secondary" href="/api/export?format=csv">Descargar CSV</a><span>Reporte diario por email: 5:00 p. m. · Panamá</span></div><div className="summary-strip"><div><small>Saldo total</small><strong>{money(d.invoices.reduce((a,i)=>a+balance(i),0))}</strong></div><div><small>Pagos con fecha de hoy</small><strong>{money(d.payments.filter(p=>p.paid_on===today()).reduce((a,p)=>a+p.amount_cents,0))}</strong></div><div><small>Promesas incumplidas</small><strong>{d.promises.filter(p=>p.status==='pendiente'&&p.due_date<today()).length}</strong></div></div><h2>Actividad del equipo hoy</h2><Table headers={['Responsable','Llamadas','Contactos efectivos','Sin respuesta']} rows={staffActivity(d.calls).map(p=>[p.name,p.calls,p.contacts,p.unanswered])}/><h2>Pagos y abonos de hoy</h2><Table headers={['Estudiante','Referencia','Monto','Responsable']} rows={d.payments.filter(p=>p.paid_on===today()).map(p=>[p.student_name,p.reference,money(p.amount_cents),p.author])}/><h2>Registro de auditoría</h2><Table headers={['Fecha','Acción','Responsable']} rows={d.audit.map(a=>[formatDate(a.created_at),a.action,a.author||'Sistema'])}/></>}
 {section==='importar'&&<Importer csrf={actor.csrf||''}/>}
 </Shell>;
}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}) {return <div className="card table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">Todavía no hay registros para mostrar.</p>}</div>;}
function Editor({title,children}:{title:string;children:React.ReactNode}) {return <details className="card editor"><summary>+ {title}</summary><div>{children}</div></details>;}
function formatDate(date:string) {return new Intl.DateTimeFormat('es-PA',{dateStyle:'short',timeStyle:'short',timeZone:'America/Panama'}).format(new Date(date));}
