'use client';
import { useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import type { ImportRow } from '@/lib/imports';
export function Importer({csrf}:{csrf:string}) {
 const [rows,setRows]=useState<ImportRow[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(0);const router=useRouter();
 async function preview(e:FormEvent<HTMLFormElement>) {e.preventDefault();setBusy(true);setError('');setRows([]);setDone(0);try{const response=await fetch('/api/import',{method:'POST',headers:{'x-csrf-token':csrf},body:new FormData(e.currentTarget)});const result=await response.json();if(!response.ok)throw new Error(result.error);setRows(result.rows);}catch(e){setError(e instanceof Error?e.message:'No se pudo leer.');}finally{setBusy(false);}}
 async function confirm(){setBusy(true);setError('');try{const response=await fetch('/api/import',{method:'POST',headers:{'x-csrf-token':csrf,'Content-Type':'application/json'},body:JSON.stringify({rows})});const result=await response.json();if(!response.ok)throw new Error(result.error);setDone(result.count);setRows([]);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo importar.');}finally{setBusy(false);}}
 return <section className="card detail-card"><h2>De Excel a tu cartera</h2><p>1. Descarga la plantilla. 2. Completa hasta 500 cuentas. 3. Revisa antes de confirmar.</p><a className="text-link" href="/api/export?template=true">Descargar plantilla Excel</a><div className="notice">Los datos importados no autorizan mensajes. Registra el consentimiento de cada acudiente después de verificarlo. Las referencias duplicadas detienen toda la importación. Los hermanos comparten ficha cuando coinciden el nombre, correo y teléfono del acudiente, con al menos un contacto. Si ya existen fichas duplicadas, deben unificarse antes de importar.</div><form className="entry-form" onSubmit={preview}><label className="field">Archivo Excel (.xlsx, máximo 2 MB)<input type="file" name="file" accept=".xlsx" required/></label><button className="button" disabled={busy}>Revisar archivo</button></form>{error&&<p className="error" role="alert">{error}</p>}{done>0&&<p className="success">Se importaron {done} cuentas correctamente.</p>}{rows.length>0&&<><h3>Vista previa: {rows.length} cuentas</h3><div className="table-scroll"><table><thead><tr><th>Estudiante</th><th>Acudiente</th><th>Referencia</th><th>Monto</th><th>Mora</th></tr></thead><tbody>{rows.slice(0,20).map((row,i)=><tr key={i}><td>{row.estudiante}</td><td>{row.acudiente}</td><td>{row.referencia}</td><td>{row.monto}</td><td>{row.mora}</td></tr>)}</tbody></table></div><p>Se muestran las primeras 20 filas. Se validaron las {rows.length} filas.</p><button className="button" disabled={busy} onClick={confirm}>{busy?'Importando…':`Confirmar importación de ${rows.length} cuentas`}</button></>}</section>;
}
