import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireActor } from '@/lib/auth';
import { getProfile,canEditProfiles } from '@/lib/profiles';
import { db } from '@/lib/db';
import { balance,money } from '@/lib/domain';
import type { Invoice } from '@/lib/types';
import { Shell } from './shell';
import { ProfileEditor,ProfileLifecycle } from './profile-editor';
import { ProfileHistory } from './profile-history';
import { positivePage } from './profiles-list';

export async function ProfilePage({entity,id,history}:{entity:'guardian'|'student';id:string;history?:string}) {
 const actor=await requireActor(),page=positivePage(history),data=await getProfile(actor,entity,id,page);if(!data)notFound();
 const {profile:g,plan}=data,section=entity==='guardian'?'acudientes':'estudiantes';
 const where=entity==='guardian'?'st.guardian_id=?':'st.id=?',args=[actor.school_id,id];
 const join='FROM ce_invoices i JOIN ce_students st ON st.school_id=i.school_id AND st.id=i.student_id';
 const [totals,accounts,payments,promises,calls,family]=await Promise.all([
  db.query<{pending:number;total:number}>(`SELECT COALESCE(SUM(i.amount_cents+i.late_fee_cents-i.paid_cents),0) AS pending,COUNT(*) AS total ${join} WHERE i.school_id=? AND ${where}`,args),
  db.query<Invoice>(`SELECT i.*,st.name AS student_name ${join} WHERE i.school_id=? AND ${where} ORDER BY i.due_date DESC,i.id LIMIT 50`,args),
  db.query<{id:string;amount_cents:number;reference:string;paid_on:string;author:string}>(`SELECT p.id,p.amount_cents,p.reference,p.paid_on,u.name AS author FROM ce_payments p JOIN ce_users u ON u.school_id=p.school_id AND u.id=p.created_by JOIN ce_invoices i ON i.school_id=p.school_id AND i.id=p.invoice_id JOIN ce_students st ON st.school_id=i.school_id AND st.id=i.student_id WHERE p.school_id=? AND ${where} ORDER BY p.created_at DESC,p.id LIMIT 25`,args),
  db.query<{id:string;amount_cents:number;due_date:string;status:string}>(`SELECT p.id,p.amount_cents,p.due_date,p.status FROM ce_promises p JOIN ce_invoices i ON i.school_id=p.school_id AND i.id=p.invoice_id JOIN ce_students st ON st.school_id=i.school_id AND st.id=i.student_id WHERE p.school_id=? AND ${where} ORDER BY p.created_at DESC,p.id LIMIT 25`,args),
  entity==='guardian'?db.query<{id:string;outcome:string;notes:string;created_at:string;author:string}>('SELECT c.*,u.name AS author FROM ce_calls c JOIN ce_users u ON u.school_id=c.school_id AND u.id=c.created_by WHERE c.school_id=? AND c.guardian_id=? ORDER BY c.created_at DESC,c.id LIMIT 25',args):Promise.resolve([]),
  entity==='student'?db.query<{name:string;archived_at:string|null}>('SELECT name,archived_at FROM ce_guardians WHERE school_id=? AND id=?',[actor.school_id,g.guardian_id]):Promise.resolve([]),
 ]);
 const editable=canEditProfiles(actor),parentArchived=!!family[0]?.archived_at;
 return <Shell actor={actor} section={section}><Link className="text-link" href={`/${section}`}>Volver a {section}</Link><div className="page-heading"><div><span className="eyebrow">FICHA DEL {entity==='guardian'?'ACUDIENTE':'ESTUDIANTE'}</span><h1>{g.name}</h1><p>{entity==='student'?`${g.code} · ${g.grade}`:'Familia y contactos'}</p><span className={`badge ${g.archived_at?'warning':'good'}`}>{g.archived_at?'Archivado':'Activo'}</span></div><div className="balance-box"><small>Saldo actual · todas las cuentas</small><strong>{money(Number(totals[0].pending))}</strong></div></div>{g.archived_at&&<div className="notice">Ficha archivada. Se conservan los movimientos y el saldo; los recordatorios de esta ficha están detenidos.</div>}
 {entity==='guardian'?<div className="detail-grid"><section className="card detail-card"><h2>Contactos de la familia</h2>{g.contacts?.map(c=><div className="contact-summary" key={c.id}><strong>{c.name} · {c.relationship==='otro'?'Otro responsable':c.relationship==='madre'?'Madre':'Padre'}</strong>{!!c.is_primary&&<p><span className="badge good">Principal para recordatorios</span></p>}<p>{c.email||'Sin correo'} · {c.phone||'Sin teléfono'}</p><small>Correo: {c.email_consent?'autorizado':'sin autorización'} · WhatsApp: {c.whatsapp_consent?'autorizado':'sin autorización'}</small>{c.consent_note&&<small>Evidencia: {c.consent_note}</small>}</div>)}</section><section className="card detail-card"><h2>Estudiantes asociados ({plan.students.length})</h2>{plan.students.map(st=><div className="account-line" key={st.id}><div><Link className="text-link" href={`/estudiantes/${st.id}`}>{st.name}</Link><small>{st.code} · {st.grade} · {st.archived_at?'Archivado':'Activo'}</small></div></div>)}{!plan.students.length&&<p>No hay estudiantes asociados.</p>}<p className="help">Para registrar un hermano, crea un estudiante y selecciona esta misma ficha de acudiente.</p></section></div>:<p>Acudiente: <Link className="text-link" href={`/acudientes/${g.guardian_id}`}>{family[0]?.name}</Link></p>}
 {editable&&!g.archived_at&&!parentArchived&&<ProfileEditor key={g.id} entity={entity} profile={g} contacts={g.contacts} guardianName={family[0]?.name} csrf={actor.csrf||''}/>}
 <div className="detail-grid profile-section"><section className="card detail-card"><h2>Cuentas por cobrar ({totals[0].total})</h2><p className="help">Se muestran hasta 50 cuentas. El saldo superior incluye todas.</p>{accounts.map(i=><div className="account-line" key={i.id}><div><strong>{i.reference} · {i.student_name}</strong><small>{i.concept} · Vence {i.due_date}</small><small>Cargo {money(i.amount_cents)} + mora {money(i.late_fee_cents)} − abonos {money(i.paid_cents)}</small></div><strong>{money(balance(i))}</strong></div>)}{!accounts.length&&<p>Sin cuentas registradas.</p>}<Link className="text-link" href={'/cobros?q='+encodeURIComponent(g.name)}>Consultar cuentas por cobrar</Link><h2 className="profile-section">Promesas recientes</h2>{promises.map(p=><p key={p.id}>{p.due_date} · {money(p.amount_cents)} · {p.status}</p>)}{!promises.length&&<p>Sin promesas registradas.</p>}</section><section className="card detail-card"><h2>Pagos recientes</h2><p className="help">Últimos 25 pagos y gestiones. El historial completo se conserva en Pagos y Seguimiento.</p>{payments.map(p=><div className="account-line" key={p.id}><div><strong>{money(p.amount_cents)} · {p.reference}</strong><small>{p.paid_on} · {p.author}</small></div></div>)}{!payments.length&&<p>Sin pagos registrados.</p>}{entity==='guardian'&&<><h2>Seguimiento reciente</h2>{calls.map(c=><div className="account-line" key={c.id}><div><strong>{c.outcome}</strong><small>{c.notes||'Sin notas'}</small><small>{c.author} · {new Date(c.created_at).toLocaleString('es-PA',{timeZone:'America/Panama'})}</small></div></div>)}</>}</section></div>
 <ProfileHistory rows={data.history} page={page} more={data.moreHistory} href={`/${section}/${id}`}/>
 {editable&&!parentArchived&&<ProfileLifecycle key={'lifecycle-'+g.version} entity={entity} id={id} version={g.version} archived={!!g.archived_at} mode={plan.mode} childrenCount={plan.students.length} csrf={actor.csrf||''}/>}{parentArchived&&<p className="notice profile-section">Reactiva primero la ficha del acudiente para modificar o reactivar a este estudiante.</p>}
 </Shell>;
}
