'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import type { Contact } from '@/lib/types';

type Draft={id?:string;name:string;relationship:'madre'|'padre'|'otro';email:string;phone:string;is_primary:boolean;email_consent:boolean;whatsapp_consent:boolean;consent_note:string};
const draft=(c:Contact):Draft=>({id:c.id,name:c.name,relationship:c.relationship,email:c.email||'',phone:c.phone||'',is_primary:!!c.is_primary,email_consent:!!c.email_consent,whatsapp_consent:!!c.whatsapp_consent,consent_note:c.consent_note||''});
async function save(action:string,data:unknown,csrf:string) {
 const response=await fetch(`/api/${action}`,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(data)});
 const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo guardar.');return result;
}
export function GuardianPicker({initial,onChange}:{initial?:{id:string;name:string};onChange?:(id:string)=>void}) {
 const [selected,setSelected]=useState(initial),[query,setQuery]=useState(''),[rows,setRows]=useState<{id:string;name:string;email:string|null;phone:string|null}[]>([]),[error,setError]=useState('');
 useEffect(()=>{const control=new AbortController();const timer=setTimeout(async()=>{try{const res=await fetch('/api/profile-guardians?q='+encodeURIComponent(query),{signal:control.signal});if(!res.ok)throw new Error('No se pudieron consultar los acudientes.');setRows((await res.json()).rows);setError('');}catch(e){if(!control.signal.aborted)setError(e instanceof Error?e.message:'Error de conexión.');}},250);return()=>{clearTimeout(timer);control.abort();};},[query]);
 return <div className="field full"><input type="hidden" name="guardian_id" value={selected?.id||''}/><label className="field">Buscar acudiente existente<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="Escribe su nombre o correo"/></label><p className="help">Seleccionado: {selected?.name||'Ninguno'}. Para hermanos, elige la misma ficha.</p>{error&&<p role="alert">{error}</p>}<select aria-label="Acudiente responsable" required value={selected?.id||''} onChange={e=>{const g=rows.find(r=>r.id===e.target.value);if(g){setSelected(g);onChange?.(g.id);}}}><option value="" disabled>Selecciona un acudiente</option>{selected&&!rows.some(r=>r.id===selected.id)&&<option value={selected.id}>{selected.name}</option>}{rows.map(g=><option key={g.id} value={g.id}>{g.name} · {g.email||g.phone||'Sin contacto'}</option>)}</select><small className="help">Hasta 25 coincidencias; escribe para precisar la búsqueda.</small></div>;
}
export function ProfileEditor({entity,profile,contacts=[],guardianName='',csrf}:{entity:'guardian'|'student';profile:{id:string;name:string;version:number;code?:string;grade?:string;guardian_id?:string};contacts?:Contact[];guardianName?:string;csrf:string}) {
 const router=useRouter(),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[items,setItems]=useState<Draft[]>(contacts.map(draft));
 function open(){setItems(contacts.map(draft));setEditing(true);setError('');setSaved(false);}
 function change(index:number,patch:Partial<Draft>){setItems(old=>old.map((c,i)=>i===index?{...c,...patch}:c));}
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy)return;setBusy(true);setError('');
  const form=new FormData(event.currentTarget);const base={id:profile.id,version:profile.version,name:String(form.get('name')),reason:String(form.get('reason'))};
  try{await save(entity+'-update',entity==='guardian'?{...base,contacts:items}:{...base,code:String(form.get('code')),grade:String(form.get('grade')),guardian_id:String(form.get('guardian_id'))},csrf);setEditing(false);setSaved(true);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo conectar.');}finally{setBusy(false);}
 }
 return <section className="card detail-card profile-section"><h2>{entity==='guardian'?'Datos y contactos':'Datos del estudiante'}</h2>{saved&&<p role="status" className="success">Cambios guardados.</p>}{!editing?<button type="button" className="button" onClick={open}>Editar</button>:<form onSubmit={submit} className="entry-form"><fieldset disabled={busy} className="profile-fields full"><label className="field">{entity==='guardian'?'Nombre de la ficha del acudiente':'Nombre completo'}<input name="name" defaultValue={profile.name} required maxLength={180}/></label>{entity==='student'&&<><label className="field">Código único<input name="code" defaultValue={profile.code} required maxLength={40}/></label><label className="field">Grado / sección<input name="grade" defaultValue={profile.grade} required maxLength={60}/></label><GuardianPicker initial={{id:profile.guardian_id||'',name:guardianName}}/><p className="help full">Si tiene movimientos, se conserva su familia actual. La deuda no se transfiere al editar la ficha.</p></>}
 {entity==='guardian'&&<div className="full"><p className="help">Añade hasta 10 contactos. Para otro teléfono o correo de la misma persona, añade otro contacto con su nombre. Los recordatorios utilizan únicamente el principal y los canales que tenga autorizados.</p>{items.map((c,index)=><fieldset className="contact-editor" key={c.id||'new-'+index}><legend>Contacto {index+1}</legend><div className="profile-fields"><label className="field">Nombre del contacto<input required maxLength={180} value={c.name} onChange={e=>change(index,{name:e.target.value,email_consent:false,whatsapp_consent:false})}/></label><label className="field">Relación<select value={c.relationship} onChange={e=>change(index,{relationship:e.target.value as Draft['relationship'],email_consent:false,whatsapp_consent:false})}><option value="madre">Madre</option><option value="padre">Padre</option><option value="otro">Otro responsable</option></select></label><label className="field">Correo electrónico<input type="email" maxLength={180} value={c.email} onChange={e=>change(index,{email:e.target.value,email_consent:false})}/></label><label className="field">Teléfono / WhatsApp<input type="tel" maxLength={16} placeholder="+50761234567" value={c.phone} onChange={e=>change(index,{phone:e.target.value,whatsapp_consent:false})}/></label><label className="check full"><input type="radio" name="primary" checked={c.is_primary} onChange={()=>setItems(items.map((item,i)=>({...item,is_primary:i===index})))}/>Principal para los recordatorios</label><label className="check"><input type="checkbox" disabled={!c.email} checked={c.email_consent} onChange={e=>change(index,{email_consent:e.target.checked})}/>Autoriza correo</label><label className="check"><input type="checkbox" disabled={!c.phone} checked={c.whatsapp_consent} onChange={e=>change(index,{whatsapp_consent:e.target.checked})}/>Autoriza WhatsApp</label><label className="field full">Evidencia de autorización o retiro<textarea maxLength={500} minLength={c.email_consent||c.whatsapp_consent?5:undefined} required={c.email_consent||c.whatsapp_consent} value={c.consent_note} onChange={e=>change(index,{consent_note:e.target.value})} placeholder="Fecha, medio y quién autorizó cada canal"/></label><button type="button" className="button secondary" disabled={items.length===1} onClick={()=>setItems(items.filter((_,i)=>i!==index).map((item,i)=>({...item,is_primary:c.is_primary?i===0:item.is_primary})))}>Quitar contacto {index+1}</button></div></fieldset>)}<button type="button" className="button secondary" disabled={items.length>=10} onClick={()=>setItems([...items,{name:profile.name,relationship:'otro',email:'',phone:'',is_primary:items.length===0,email_consent:false,whatsapp_consent:false,consent_note:''}])}>Añadir otro teléfono o correo</button></div>}
 <label className="field full">Motivo del cambio<textarea name="reason" required minLength={5} maxLength={500} placeholder="Por ejemplo: la madre confirmó su nuevo teléfono"/></label>{entity==='guardian'&&<p className="help full">Al cambiar una persona, correo o teléfono, su autorización se retira hasta registrar una nueva evidencia.</p>}</fieldset>{error&&<p role="alert" className="error">{error}</p>}<div className="profile-actions full"><button className="button" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button><button className="button secondary" type="button" disabled={busy} onClick={()=>{setEditing(false);setError('');}}>Cancelar</button></div></form>}</section>;
}
export function ProfileLifecycle({entity,id,version,archived,mode,childrenCount,csrf}:{entity:'guardian'|'student';id:string;version:number;archived:boolean;mode:'archive'|'delete';childrenCount:number;csrf:string}) {
 const router=useRouter(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const label=archived?'Reactivar':mode==='archive'?'Archivar':'Eliminar';
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const reason=String(new FormData(event.currentTarget).get('reason'));try{await save(archived?'profile-restore':'profile-remove',{entity,id,version,mode,reason},csrf);setOpen(false);if(!archived&&mode==='delete')router.push(entity==='guardian'?'/acudientes':'/estudiantes');router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo conectar.');}finally{setBusy(false);}}
 return <section className="card detail-card profile-section"><h2>{label} ficha</h2><p>{archived?'La ficha volverá a estar disponible para registrar información.':mode==='archive'?'Tiene movimientos: se conservarán las deudas, pagos, promesas e historial. Sus recordatorios se detendrán.':'No tiene movimientos. La ficha se borrará; la acción quedará registrada en auditoría.'}</p>{entity==='guardian'&&<p>{archived?'Los estudiantes permanecerán archivados hasta reactivarlos individualmente.':`${childrenCount} estudiante(s) asociados se ${mode==='archive'?'archivarán':'eliminarán'} con esta familia.`}</p>}{!open?<button type="button" className="button secondary" onClick={()=>setOpen(true)}>{label} ficha</button>:<form className="entry-form" onSubmit={submit}><label className="field full">Motivo<textarea name="reason" required minLength={5} maxLength={500} disabled={busy}/></label><label className="check full"><input type="checkbox" required disabled={busy}/>Confirmo que deseo {label.toLowerCase()} esta ficha{!archived&&entity==='guardian'?' y sus estudiantes asociados':''}.</label>{error&&<p className="error" role="alert">{error}</p>}<div className="profile-actions full"><button disabled={busy} className="button">{busy?'Guardando…':`Confirmar: ${label.toLowerCase()}`}</button><button disabled={busy} className="button secondary" type="button" onClick={()=>setOpen(false)}>Cancelar</button></div></form>}</section>;
}
