import Link from 'next/link';
import { Shell } from './shell';
import { Form,Field } from './form';
import { GuardianPicker } from './profile-editor';
import { canEditProfiles,listProfiles } from '@/lib/profiles';
import type { Actor } from '@/lib/types';
export function positivePage(value?:string) {return Math.max(1,Math.min(100000,Number.parseInt(value||'1',10)||1));}
export async function ProfilesList({actor,entity,query}:{actor:Actor;entity:'guardian'|'student';query:{q?:string;archivo?:string;page?:string}}) {
 const section=entity==='guardian'?'acudientes':'estudiantes',archived=query.archivo==='si',page=positivePage(query.page),q=(query.q||'').slice(0,100);
 const {rows,total}=await listProfiles(actor,entity,q,archived,page);const href=(p:number)=>`/${section}?`+new URLSearchParams({q,archivo:archived?'si':'no',page:String(p)});
 return <Shell actor={actor} section={section}><div className="page-heading"><div><span className="eyebrow">GESTIÓN DEL COLEGIO</span><h1>{entity==='guardian'?'Acudientes':'Estudiantes'}</h1><p>{entity==='guardian'?'Una ficha por familia, con todos sus contactos y estudiantes.':'Consulta su familia, actualiza sus datos y conserva su historial.'}</p></div></div><form className="filters"><input aria-label="Buscar fichas" name="q" defaultValue={q} maxLength={100} placeholder={entity==='guardian'?'Buscar por nombre o correo principal':'Buscar por nombre o código'}/><select name="archivo" aria-label="Estado de las fichas" defaultValue={archived?'si':'no'}><option value="no">Activos</option><option value="si">Archivados</option></select><button className="button secondary">Buscar</button></form><p className="help">{total} fichas · Página {page} · Hasta 50 por página</p><div className="card table-scroll"><table><thead><tr>{(entity==='guardian'?['Nombre','Contacto principal','Estudiantes','Canales autorizados','Ficha']:['Código','Estudiante','Grado','Acudiente','Ficha']).map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{entity==='guardian'?<><td>{r.name}</td><td>{r.email||'Sin correo'}<small>{r.phone||'Sin teléfono'}</small></td><td>{r.student_count}</td><td>{[r.email_consent?'Correo':'',r.whatsapp_consent?'WhatsApp':''].filter(Boolean).join(' · ')||'Sin autorización'}</td></>:<><td>{r.code}</td><td>{r.name}</td><td>{r.grade}</td><td><Link href={`/acudientes/${r.guardian_id}`}>{r.guardian_name}</Link></td></>}<td><Link className="text-link" href={`/${section}/${r.id}`}>Ver ficha</Link></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No hay fichas con estos filtros.</p>}</div><nav className="profile-actions profile-section" aria-label="Páginas de fichas">{page>1&&<Link href={href(page-1)}>Anterior</Link>}{page*50<total&&<Link href={href(page+1)}>Siguiente</Link>}</nav>{canEditProfiles(actor)&&!archived&&<details className="card editor"><summary>+ Registrar {entity==='guardian'?'acudiente':'estudiante'}</summary><div><Form action={entity} csrf={actor.csrf}><Field name="name" label="Nombre completo"/>{entity==='guardian'?<><Field name="email" type="email" required={false} label="Correo principal"/><Field name="phone" required={false} label="Teléfono principal" placeholder="+50761234567"/><Field name="consent_note" required={false} label="Evidencia de autorización"/><label className="check"><input type="checkbox" name="email_consent"/>Autoriza correo</label><label className="check"><input type="checkbox" name="whatsapp_consent"/>Autoriza WhatsApp</label><p className="help full">Después de guardar, abre su ficha para añadir contactos e identificar a la madre, padre u otro responsable.</p></>:<><Field name="code" label="Código único"/><Field name="grade" label="Grado / sección"/><GuardianPicker/></>}</Form></div></details>}</Shell>;
}
